'use client';
import {useState} from 'react';
import {Store,Package,Plus,Layers,Clock,ArrowUpRight} from 'lucide-react';
import {api,s,useData,useSearch,State,Empty,SearchBox,Pager,Modal,Form,saved} from './shared';
const tabs=['Products','Categories','Inventory','Orders','Customers','Payments & revenue'];
export default function Marketplace(){
 const [tab,setTab]=useState('Products');const [page,setPage]=useState(1);
 const [text,setText,search]=useSearch();const data=useData('/marketplace-admin?q='+encodeURIComponent(search)+'&page='+page);
 const [editing,setEditing]=useState(null);const [category,setCategory]=useState(false);
 const d=data.data;const counts=d?.summary||{};
 return <><div className={s.heading}><div><small>MORE FOR STUDENT LIFE</small><h1>Marketplace</h1><p>Prepare a thoughtful collection for your campus community.</p></div><button className={s.primary} disabled={data.loading||Boolean(data.error)} onClick={()=>setEditing({})}><Plus size={17}/> Add product</button></div>
 <section className={s.card} style={{background:'linear-gradient(120deg,rgba(52,125,108,.16),rgba(102,154,171,.10))',marginBottom:20}}><div className={s.cardTitle}><h2><Store size={22}/> A new chapter, coming soon.</h2><span className={s.badge}>Pre-launch</span></div><p>Build your catalogue here. Products stay private while the student marketplace is coming soon. Marking a product ready does not publish it or enable checkout.</p></section>
 <State resource={data}><div className={s.kpis}>{[['Products',counts.total,Package],['Drafts',counts.drafts,Clock],['Ready for launch',counts.ready,Store],['Out of stock',counts.out_of_stock,Layers]].map(([title,value,Icon])=><section className={s.card} key={title}><span className={s.icon}><Icon size={20}/></span><small>{title}</small><strong>{Number(value||0).toLocaleString()}</strong></section>)}</div></State>
 <div className={s.actions} style={{flexWrap:'wrap',margin:'20px 0'}} aria-label="Marketplace sections">{tabs.map(t=><button key={t} aria-pressed={tab===t} className={tab===t?s.primary:undefined} onClick={()=>{setTab(t);setPage(1);}}>{t}</button>)}</div>
 {['Products','Inventory'].includes(tab)&&<section className={s.card}><div className={s.cardTitle}><h2>{tab}</h2><SearchBox value={text} onChange={v=>{setText(v);setPage(1);}} placeholder="Search product titles…"/></div><State resource={data}>{d?.products.length?<><div className={s.tableWrap}><table><thead><tr><th>Product</th><th>Audience</th><th>Price</th><th>Availability</th><th>Status</th><th>Manage</th></tr></thead><tbody>{d.products.map(p=><tr key={p.id}><td><b>{p.title}</b><div className={s.muted}>{p.category_name}</div></td><td>{p.institution_name||'All institutions'}</td><td>₦{(p.price_kobo/100).toLocaleString('en-NG',{minimumFractionDigits:2})}</td><td>{p.format==='digital'?'Digital':`${p.stock} in stock`}</td><td><span className={s.badge}>{p.status}</span></td><td><button aria-label={'Edit '+p.title} onClick={()=>setEditing(p)}>Edit <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div><Pager data={d} page={page} setPage={setPage}/></>:<Empty>No products yet. Add your first product to prepare for launch.</Empty>}</State></section>}
 {tab==='Categories'&&<section className={s.card}><div className={s.cardTitle}><h2>Categories</h2><button onClick={()=>setCategory(true)}><Plus size={17}/> Add category</button></div><State resource={data}>{d?.categories.length?d.categories.map(c=><div className={s.rank} key={c.id}><Layers size={18}/><b>{c.name}</b></div>):<Empty>Create categories to organise your collection.</Empty>}</State></section>}
 {['Orders','Customers','Payments & revenue'].includes(tab)&&<section className={s.card}><Empty><Store size={30}/><h2>{tab} will open at launch</h2><p>Student purchases are not enabled yet. Your existing KP wallet and free learning library continue to work as usual.</p></Empty></section>}
 {editing&&<ProductEditor item={editing} categories={d?.categories||[]} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);data.reload();saved('Product saved for launch');}}/>}
 {category&&<Modal title="Create a category" onClose={()=>setCategory(false)}><Form fields={[{key:'name',label:'Category name',maxLength:100}]} onCancel={()=>setCategory(false)} onSave={async v=>{await api.post('/marketplace-admin/categories',v);setCategory(false);data.reload();saved('Category created');}}/></Modal>}
 </>;
}
function ProductEditor({item,categories,onClose,onSaved}){
 const institutions=useData('/institutions');
 const fields=[{key:'title',label:'Product title',maxLength:180},{key:'description',label:'Description',type:'textarea',optional:true},{key:'category_id',label:'Category',options:categories.map(c=>({value:c.id,label:c.name}))},{key:'institution_id',label:'Institution — leave blank for all institutions',optional:true,options:(institutions.data||[]).map(i=>({value:i.id,label:i.name}))},{key:'format',label:'Format',options:['digital','physical']},{key:'price_naira',label:'Price (₦)',type:'text',maxLength:12},{key:'stock',label:'Physical stock count (ignored for digital)',type:'number',min:0,max:1000000,optional:true},{key:'status',label:'Preparation status',options:['draft','ready','archived']}];
 return <Modal title={item.id?'Edit product':'Add product'} onClose={onClose}><State resource={institutions}>{!categories.length?<p>Create a category in the Categories tab before adding a product.</p>:<Form initial={{...item,format:item.format||'digital',status:item.status||'draft',price_naira:(item.price_kobo||0)/100,stock:item.stock??0}} fields={fields} onCancel={onClose} submit="Save product" onSave={async v=>{const body={title:v.title,description:v.description||'',category_id:v.category_id,institution_id:v.institution_id||null,format:v.format,price_kobo:Math.round(Number(v.price_naira)*100),stock:Number(v.stock),status:v.status};if(item.id)await api.patch('/marketplace-admin/products/'+item.id,body);else await api.post('/marketplace-admin/products',body);onSaved();}}/>}</State></Modal>;
}
