'use client';
import {useEffect,useState} from 'react';
import {Users,Plus,ArrowRight} from 'lucide-react';
import {useAuth} from '@/context/AuthContext';
import {s,api,useData,useSearch,State,Empty,SearchBox,Pager,Modal,Form,Confirm,saved,date,number} from './shared';
export default function People({team=false}){
 const {user}=useAuth();const [value,setValue,search]=useSearch();const [institution,setInstitution]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [selected,setSelected]=useState(null);const [add,setAdd]=useState(false);
 const schools=useData('/manage/institutions');useEffect(()=>setPage(1),[search,institution,status,team]);
 const r=useData('/admin-console/users?'+new URLSearchParams({role:team?'team':'student',search,institution,status,page}));
 return <><div className={s.heading}><div><small>{team?'ACCESS & PERMISSIONS':'YOUR LEARNING COMMUNITY'}</small><h1>{team?'Team management':'Student management'}</h1><p>{team?'Manage staff accounts and their access.':'Find students, review their activity and manage account access.'}</p></div>{team&&user.role==='super_admin'&&<button className={s.primary} onClick={()=>setAdd(true)}><Plus size={17}/> Add team member</button>}</div><section className={s.card}><div className={s.toolbar}><SearchBox value={value} onChange={setValue} placeholder="Search name or email…"/>{!team&&<select aria-label="Filter by institution" value={institution} onChange={e=>setInstitution(e.target.value)}><option value="">All institutions</option>{schools.data?.map(x=><option key={x.id} value={x.id}>{x.short_name}</option>)}</select>}<select aria-label="Account status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="unverified">Unverified</option></select></div><State resource={r}>{r.data?.rows.length?<><div className={s.tableWrap}><table><thead><tr><th>{team?'Team member':'Student'}</th><th>{team?'Role':'Institution'}</th><th>Status</th><th>Joined</th><th/></tr></thead><tbody>{r.data.rows.map(x=><tr key={x.id}><td><button className={s.entity} onClick={()=>setSelected(x.id)}><span className={s.avatar}>{x.full_name?.slice(0,1)}</span><span><b>{x.full_name}</b><small>{x.email}</small></span></button></td><td>{team?x.role.replaceAll('_',' '):x.institution_name||'Not selected'}</td><td><span className={x.is_suspended?s.warning:s.badge}>{x.is_suspended?'Suspended':'Active'}</span>{!x.is_verified&&<small className={s.muted}>Unverified email</small>}</td><td>{date(x.created_at)}</td><td><button aria-label={`View ${x.full_name}`} onClick={()=>setSelected(x.id)}><ArrowRight size={18}/></button></td></tr>)}</tbody></table></div><Pager data={r.data} page={page} setPage={setPage}/></>:<Empty>No accounts match these filters.</Empty>}</State></section>{selected&&<Person id={selected} onClose={()=>{setSelected(null);r.reload();}}/>}{add&&<Modal title="Add team member" onClose={()=>setAdd(false)}><p>Create an admin or lecturer account. Share the initial password with them directly; no invitation email is sent.</p><Form fields={[{key:'full_name',label:'Full name'},{key:'email',label:'Email',type:'email'},{key:'password',label:'Initial password',type:'password',minLength:8,maxLength:72},{key:'role',label:'Role',options:['admin','lecturer']}]} initial={{role:'admin'}} onCancel={()=>setAdd(false)} onSave={async values=>{await api.post('/admin/users',values);saved('Team member created');setAdd(false);r.reload();}}/></Modal>}</>;
}
function Person({id,onClose}){
 const r=useData('/admin-console/users/'+id);const {user,setUser}=useAuth();const [editing,setEditing]=useState(false);const [role,setRole]=useState('');const [confirm,setConfirm]=useState(null);const [err,setErr]=useState('');const [busy,setBusy]=useState(false);const x=r.data;
 const canEdit=x&&(x.role==='student'||(user.role==='super_admin'&&x.role!=='super_admin')||x.id===user.id);
 async function action(){setBusy(true);setErr('');try{if(confirm==='role')await api.patch(`/admin/users/${id}/role`,{role});else await api.patch(`/admin-console/users/${id}/suspension`,{is_suspended:!x.is_suspended});saved();setConfirm(null);r.reload();}catch(e){setErr(e.response?.data?.message||'Unable to update account');}finally{setBusy(false);}}
 return <Modal wide title={x?.full_name||'Account details'} onClose={()=>!busy&&onClose()}><State resource={r}>{x&&(editing?<Form initial={x} fields={[{key:'full_name',label:'Full name'},{key:'phone',label:'Phone',optional:true}]} onCancel={()=>setEditing(false)} onSave={async values=>{await api.patch('/admin-console/users/'+id,values);if(id===user.id)setUser({...user,full_name:values.full_name,phone:values.phone});saved();setEditing(false);r.reload();}}/>:confirm?<><h3>{confirm==='role'?`Change role to ${role}?`:x.is_suspended?'Reactivate this account?':'Suspend this account?'}</h3><p>{confirm==='role'?'The user’s permissions will change immediately.':'Suspension blocks login and authenticated API access. Academic records and wallet history stay intact.'}</p>{err&&<p role="alert" className={s.error}>{err}</p>}<div className={s.actions}><button disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button><button disabled={busy} className={s.primary} onClick={action}>{busy?'Saving…':'Confirm'}</button></div></>:<><div className={s.profileHero}><span className={s.avatar}>{x.full_name?.slice(0,1)}</span><div><h3>{x.full_name}</h3><p>{x.email}</p><span className={x.is_suspended?s.warning:s.badge}>{x.is_suspended?'Suspended':'Active'}</span></div></div><div className={s.facts}>{[['Role',x.role.replaceAll('_',' ')],['Phone',x.phone],['Institution',x.institution_name],['Department',x.department_name],['Level',x.level],['Matric number',x.matric_number],['Joined',date(x.created_at)],['Last login',date(x.last_login_at)],['Completed tests',number(x.completed_tests)],['AI conversations',number(x.ai_sessions)]].map(([label,val])=><div key={label}><small>{label}</small><b>{val||'Not supplied'}</b></div>)}</div>{canEdit&&<div className={s.actions}><button onClick={()=>setEditing(true)}>Edit contact details</button>{x.id!==user.id&&<button onClick={()=>{setErr('');setConfirm('suspend');}}>{x.is_suspended?'Reactivate':'Suspend'} account</button>}</div>}{user.role==='super_admin'&&x.role!=='super_admin'&&x.id!==user.id&&<div className={s.roleControl}><label>Change role<select value={role} onChange={e=>setRole(e.target.value)}><option value="">Choose role…</option>{['student','tutor','lecturer','admin'].map(v=><option key={v}>{v}</option>)}</select></label><button disabled={!role||role===x.role} onClick={()=>{setErr('');setConfirm('role');}}>Review change</button></div>}</>)}</State></Modal>;
}
